### ISSUE TITLE
Come on captain... V20 V26

### ISSUE THREAD

**Issue by Claycorp** [CCM-Modding/Nucleum-Omnium#1]
http://pastebin.com/tSp8HkvB

**Comment by CaptainShadows** [comment]
I know, I've been trying to solve that for the last 4 hours.....

Also, it is a bug with compression not Nucleum

**Comment by Hologuardian** [comment]
Capitan pls.

**Comment by CaptainShadows** [comment]
@Hologuardian Do I have to also say that the bug was because FML was not reading my mcmod.info?
